# Generated by Django 5.0 on 2024-01-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
