# Generated by Django 5.0 on 2024-01-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0004_roles_timestamp_sectors_timestamp_soul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soul',
        ),
    ]
