# Generated by Django 4.2.3 on 2024-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0005_delete_soul'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geolocation',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
