# Generated by Django 5.0 on 2024-01-06 18:11

import App_Users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0006_user_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=App_Users.models.LowercaseEmailField(max_length=50, unique=True),
        ),
    ]
