# Generated by Django 5.0 on 2024-01-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0008_user_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
