# Generated by Django 5.0 on 2024-01-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0009_remove_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('auth_code', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
