# Generated by Django 5.0 on 2024-01-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0010_authcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='geolocation',
            new_name='team',
        ),
    ]
