# Generated by Django 5.0 on 2024-01-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0011_rename_geolocation_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='sector',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Users.sectors'),
        ),
    ]
