# Generated by Django 5.0 on 2024-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0012_alter_authcode_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
