# Generated by Django 5.0 on 2024-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0013_alter_authcode_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
