# Generated by Django 5.0 on 2024-10-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='role',
        ),
        migrations.RemoveField(
            model_name='authcode',
            name='sector',
        ),
    ]
