# Generated by Django 5.0 on 2024-08-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
