# Generated by Django 5.0 on 2024-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0003_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
