# Generated by Django 5.0 on 2024-08-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
